KYLIN-4523 Fix 'LinkageError' error after upgrading httpclient version to 4.3.6
Problems:
After upgrading httpclient version to 4.3.6, on CDH 5.7 env it will lead to LinkageError occured, because it loades 'HttpContext' class in two different ClassLoader (CustomizedWebappClassloader and AppClassLoader):

Error message below:
java.lang.LinkageError: loader constraint violation: when resolving method "org.apache.http.protocol.HttpCoreContext.<init>(Lorg/apache/http/protocol/HttpContext;)V" the class loader (instance of org/apache/kylin/ext/CustomizedWebappClassloader) of the current class, org/apache/http/client/protocol/HttpClientContext, and the class loader (instance of sun/misc/Launcher$AppClassLoader) for the method's defining class, org/apache/http/protocol/HttpCoreContext, have different Class objects for the type org/apache/http/protocol/HttpContext used in the signature