KYLIN-4598 Missing dependency when run kylin.sh org.apache.kylin.*
Problems:
It throws 'NoClassDefFoundError: org/apache/kafka/clients/producer/Producer' when run kylin.sh org.apache.kylin.source.kafka.util.KafkaSampleProducer.

Solutions:
Add 'export kafka_dependency' before export HBASE_CLASSPATH in kylin.sh