KYLIN-4694 Fix 'NoClassDefFoundError: Lcom/esotericsoftware/kryo/io/Output' when query with sparder on yarn
Fix 'NoClassDefFoundError: Lcom/esotericsoftware/kryo/io/Output' when query with sparder on yarn.

Root cause:
Class 'com/esotericsoftware/kryo/io/Output' is loaded by SparkClassLoader, but there are some classes which are loaded by SparkClassLoader's parent classloader using this class.